<a href="https://colab.research.google.com/github/kezamamio/CpE-AIML/blob/main/58034_Lab02_TrashTakers.ipynb%20/%2058034_Lab02_TrashTakers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Topic02a : Prelim Problem Set I

## Case 1
Represent the following representations into its vectorized form using LaTeX.
> **Problem 1.a. System of Linear Equations**
$$
\left\{
    \begin{array}\\
        -y+z=\frac{1}{32}\\ 
        \frac{1}{2}x -2y=0 \\
        -x + \frac{3}{7}z=\frac{4}{5}
    \end{array}
\right. $$
> **Problem 1.b. Linear Combination**
$$  \cos{(\theta)}\hat{i} + \sin{(\theta)}\hat{j} - \csc{(2\theta)}\hat{k}$$
> **Problem 1.c. Scenario**
>
>A conference has 200 student attendees, 45 professionals, and has 15 members of the panel. There is a team of 40 people on the organizing committee. Represent the *percent* composition of each *attendee* type of the conference in matrix form.

Express your answers in LaTeX in the answer area.


###Answer to Problem 1.a: System of Linear Equations

> Let the vectorized form be solved using the equation $r = X^{-1}Y$ wherein, we're solving for $r$ or simply solving for $x,y,$and$z$.

> Wherein, $X$ is $\begin{bmatrix}0 & -1 &1 \\ 1/2 &-2 &0 \\ -1 & 0 & 3/7 \end{bmatrix}$,  $r$ is $\begin{bmatrix}x\\ y\\ z\end{bmatrix}$, and $Y$ is $\begin{bmatrix}1/32\\0\\4/5\end{bmatrix}$.

**Matrix**
> This is the matrix equivalent of the given form.

$$\begin{bmatrix}0 & -1 &1 \\ 1/2 &-2 &0 \\ -1 & 0 & 3/7 \end{bmatrix} \cdot\begin{bmatrix} x\\y\\z\end{bmatrix} = \begin{bmatrix}1/32\\0\\4/5\end{bmatrix}$$


In [ ]:
### Problem 1.a
import numpy as np
import fractions
from fractions import Fraction

X = np.array([
    [0,-1, 1],
    [Fraction(1,2),-2,0],
    [-1, 0, Fraction(3,7)]
 ], dtype=float)

Y = np.array([
    [Fraction(1,32)],
    [0],
    [Fraction(4,5)]
], dtype=float)

X_inv = np.linalg.inv(X)
np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())})
X_inv

array([[12/25, -6/25, -28/25],
       [3/25, -14/25, -7/25],
       [28/25, -14/25, -7/25]])

> This is the answer when computing for the inverse of the matrix.

$$\begin{bmatrix}12/25 & -6/25 & -28/25 \\ 3/25 & -14/25 & -7/25 \\ 28/25 & -14/25 & -7/25 \end{bmatrix}$$

> The answer for vector $r$. 
$$r =\begin{bmatrix}-881/1000\\-881/4000\\-189/1000\end{bmatrix}$$



In [ ]:
r = X_inv @ Y
r

array([[-881/1000],
       [-881/4000],
       [-189/1000]])

###Answer to Problem 1.b: Linear Combination

>Suppose that vector A is,$$ A= \cos{(\theta)}\hat{i} + \sin{(\theta)}\hat{j} - \csc{(2\theta)}\hat{k}$$

>then the matrix equivalent is:
$$ A = \begin{bmatrix} cos{\theta} & \sin{\theta} & -\csc{2\theta} \end{bmatrix}$$


> In this scenario, let us suppose that the value of theta $θ$ is $π/4$.

In [ ]:
import numpy as np
π = np.pi
θ = π/4

A = np.array([np.cos(θ), np.sin(θ), -np.arcsin(θ**2)])
print(A)


[ 0.70710678  0.70710678 -0.66473461]


###Answer to Problem 1.c: Scenario

>Let, $a$, $b$, $c$ and $d$ represent the type of people inside the conference.

$$\\ a = 200 \text{ students }, b = 45 \text{ professionals},c = 15 \text{ members of panel}, d = 40 \text{ organizing committee}$$ 

>Since the only ones asked are the attendees, we take only the students, professionals, and the panel members in the equation. We leave the members organizing committe as they are not considered as attendees, but rather, organizers. Let,

$$X = 200a + 45b + 15c$$

>then, the matrix equivalent is:
$$ \begin{bmatrix} 200/260 & 45/260 & 15/260 \end{bmatrix} \cdot\begin{bmatrix} a\\b\\c\end{bmatrix} = \begin{bmatrix} 1\end{bmatrix}$$




# Case 2
> **Problem 2.a: Vector Magnitude**

>The magnitude of a vector is usually computed as:
$$||v|| = \sqrt{a_0^2 + a_1^2 + ... +a_n^2}$$
Whereas $v$ is any vector and $a_k$ are its elements wherein $k$ is the size of $v$.
Re-formulate $||v||$ as a function of an inner product. Further discuss this concept and provide your user-defined function.

> **Problem 2.b: Angle Between Vectors**

> Inner products can also be related to the Law of Cosines. The property suggests that:
$$u\cdot v = ||u||\cdot||v||\cos(\theta)$$
Whereas $u$ and $v$ are vectors that have the same sizes and $\theta$ is the angle between $u$ and $v$.

> Explain the behavior of the dot product when the two vectors are perpendicular and when they are parallel.


###Answer to Problem 2.a: Vector Magnitude

> Consider vector $v$
$$||v|| = \begin{bmatrix} 
1, 2, 3, 4\\
\end{bmatrix}$$

> If we get the *inner product* of $v$ to itself, then:
$$v \cdot v = \begin{bmatrix} 
1, 2, 3, 4\\ 
\end{bmatrix} \cdot 
\begin{bmatrix} 
1, 2, 3, 4\\ 
\end{bmatrix}$$

$$v \cdot  v = \begin{bmatrix}
{(1 \cdot 1) + (2 \cdot 2) + (3 \cdot 3) + (4 \cdot 4)}\
\end{bmatrix}$$

$$v \cdot  v = \begin{bmatrix}
{1^2 + 2^2 + 3^2 + 4^2}\
\end{bmatrix}$$

> The equation above is equivalent to finding the length or magnitude of a vector. We can write the definition of length in terms of the inner product:

$$||v|| = \sqrt{v \cdot  v}$$ 

> With further simplification (square both sides), the new length definition of a vector becomes:

$$||v||^2 = v \cdot  v$$ 

In [ ]:
### Code to Problem 2.a
import numpy as np

## define vector v
v = np.array([1, 2, 3, 4])

## user-defined function
def innerProd (x):
  sum = 0
  for i in range (len(x)):
    sum += x[i] * x[i]
  return sum

## v dot v (v dot product to itself)
product = innerProd(v)
print("v dot v = ", product)

v dot v =  30


###Answer to Problem 2.b: Angle between Vectors

**Perpendicular**: Two vectors are said to be perpendicular if the result of their ***dot product is 0***. The angle between them is *90 degrees*.

Consider vectors $u$ and $v$
$$u = \begin{bmatrix} 
1, -3 \\ 
\end{bmatrix} 
$$

$$v =\begin{bmatrix} 
6, 2 \\
\end{bmatrix}
$$

The dot product is as follows:

$$u\cdot v = (1 \cdot 6) + (-3 \cdot 2)$$

$$u\cdot v = 6 - 6 = 0$$

**Parallel**: If vectors are ***multiples of each other***, they are said to be parallel. The angles between them lies on *0 or 180 degrees*.

Consider vectors $y$ and $z$
$$y = \begin{bmatrix} 
5, 2 \\ 
\end{bmatrix} 
$$

$$z =\begin{bmatrix} 
25, 10 \\
\end{bmatrix}
$$

Then, $z$ can be expressed as: 

$$z = 5y$$

Another way to confirm if vectors are parallel is by finding the angle between the two vectors using ***dot product*** and ***vector magnitude***.

$$\theta = \arccos\left(\frac{\mathbf{y}\cdot\mathbf{z}}{\|\mathbf{y}\|\|\mathbf{z}\|}\right)$$

Substituting the values we will get:

$$\theta = \arccos\left(\frac{{145}}{\|\mathbf{\sqrt{29}}\|\|\mathbf{\sqrt{725}}\|}\right)$$

$$\theta = 0$$

Therefore, they are parallel.

In [ ]:
### Code to Problem 2.b (Perpendicular)
import numpy as np

u = np.array([1, -3])
v = np.array([6, 2])

def innerProd (a, b):
  sum = 0
  for i in range (len(a)):
    sum += a[i] * b[i]
  return sum

product = innerProd(u, v)
print("u dot v = ", product)

u dot v =  0


In [ ]:
### Code to Problem 2.b (Parallel)
import numpy as np

y = np.array([5, 2])
z = np.array([25, 10])

def innerProd (a, b):
  sum = 0
  for i in range (len(a)):
    sum += a[i] * b[i]
  return sum

product = innerProd(y, z)
print("y dot z = ", product)

y dot z =  145


# Case 3
For the final cases analysis we will be looking at series of equations building up a single feed-forward computation of a logistic regression. The case will not require you to learn fully what is logistic regression. 

$$X = \begin{bmatrix} 
— (x^{(1)})^T— \\ 
— (x^{(2)})^T— \\
\vdots \\
— (x^{(m)})^T— \\
\end{bmatrix} \text{, } 
Y = \begin{bmatrix} 
y^{(1)} \\ 
y^{(2)} \\
\vdots \\
y^{(m)} \\
\end{bmatrix} \text{, and } 
\theta = \begin{bmatrix} 
\theta^{(1)} \\ 
\theta^{(2)} \\
\vdots \\
\theta^{(m)} \\
\end{bmatrix} $$
The dataset $X$ has $m$ entries with $n$ features while $Y$ is the vector containing the ground truths of a the entries of $X$, and $\theta$ are the parameters or weights of the vectors. We first compute the vector product of the dataset and the parameters as:
$$ z = x^{(i)}\theta^{(i)} = X\cdot \theta\\_{\text{Eq. 3.1}}$$
We then solve for the hypothesis of the logistic regression alogrithm as:

$$ h_\theta(x) = g(z)\\_{\text{Eq. 3.2}}$$

Where $g$ is an activation function that maps the values of the hypothesis vector between a range of 0 and 1. We computed the activation as a sigmoid function:
$$g(z) = \frac{1}{1+e^{-z}}\\_{\text{Eq. 3.3}}$$
Finally we compute the loss of the logistic regression algorithm using $J$. Wheras $J(\theta)$ is a function that computes the logistic loss of the hypothesis with respect to the ground truths $y$. it is then computed as:
$$J(\theta) = \frac{1}{m} \sum^m_{i=0}=[-y^{(i)}\log({h_{\theta}(x^{(i)})})-(1-y^{(i)})\log(1-h_{\theta}(x^{(i)}))]\\_{\text{Eq. 3.4}}$$

> **Problem 3.a: Matrix Equivalences**

> In Eq. 1, $z$ can also be solved as $X \cdot \theta$ which is the vectorized form of $x^{(i)}\theta^{(i)}$. However, it can also be expressed as $\theta^T\cdot X$. Prove the equality of $X \cdot \theta$ with $\theta^T\cdot X$ in this case.

> **Problem 3.b: Matrix Shapes**

> Determine the shape of $h_\theta$ if $X$ has a shape of $(300,5)$.

> **Problem 3.c: Vectorization**

> Express $J(\theta)$ into its vectorized form.

> **Problem 4.c: Computational Programming (Also Laboratory 2)**

> Encode Equations 3.1 to 3.4 as the class `LRegression` wherein:

> * `LRegression` should be instantiated with a dataset $X$, a ground truth vector $y$, and a parameter vector $\theta$. Each parameter should have a data type of `numpy.array`.
> * It should further have `methods`reflecting to at least the four (4) aforementioned equations. Each should have a return value.


### **Answer for Problem 3.a**

Performing the vector product of $X \cdot \theta$  will result as:

$$z = \begin{bmatrix} 
(x^{(1)})^T\theta^{(1)}\\(x^{(2)})^T\theta^{(2)}\\\vdots\\(x^{(m)})^T\theta^{(m)} \\
\end{bmatrix}
$$

Determining the transpose vector of $\theta$ will produce:

$$\theta^T = \begin{bmatrix}
(\theta^{(1)})^T\\(\theta^{(2)})^T\\\vdots\\(\theta^{(m)})^T
\end{bmatrix}
$$

Performing the vector product of $\theta^T \cdot X$ will result as:

$$z = \begin{bmatrix} 
(\theta^{(1)})^T(x^{(1)})^T\\(\theta^{(2)})^T(x^{(2)})^T\\\vdots\\(\theta^{(m)})^T(x^{(m)})^T\\
\end{bmatrix} 
$$
 
Having a generalized form of:

$$\theta^T\cdot X$$

Hence, looking back at both equations:

$$z = \begin{bmatrix} 
(x^{(1)})^T\theta^{(1)}\\(x^{(2)})^T\theta^{(2)}\\\vdots\\(x^{(m)})^T\theta^{(m)} \\
\end{bmatrix} \text { = }
\begin{bmatrix} 
(\theta^{(1)})^T(x^{(1)})^T\\(\theta^{(2)})^T(x^{(2)})^T\\\vdots\\(\theta^{(m)})^T(x^{(m)})^T\\
\end{bmatrix} 
$$

Thus, the equality of the statement $X \cdot \theta = \theta^T\cdot X$ is true.

### **Answer to Problem 3.b**
Performing the dot product of matrices requires the first matrix's number of columns equal to the second matrix's number of rows. In this case: $$X = (300, 5) \\ \theta = (5, 1)$$

Assuming the matrix $\theta$ is a column matrix, it has a $(5, 1)$ shape and its row is equal to the number of columns of the $X$ dataset. \\

Then, $h_\theta = X \cdot \theta$

Thus, the shape of $h_\theta$ is $(300, 1)$.


### **Answer to Problem 3.c**

Vectorized form of $J(\theta)$ :
$$J(\theta) = \frac{1}{m} \cdot(-y^{T}\log(h_{\theta})-(1-y)^{T}\log(1-h_{\theta}))$$

###**Answer to Case 4**

In [ ]:
class LRegression:
  def __init__(self,X,Y,theta):
    self.X = X
    self.Y = Y
    self.theta = theta
    self.Z=None
    self.g=None
    self.J=None

  def get_vectorproduct(self):
    self.Z = np.dot(self.X,self.theta)
    return self.Z

  def get_shapeh(self):
    return self.Z.shape

  def get_hypothesis(self):
    zexp = np.exp(-(self.Z))
    self.g = 1 / (1+zexp)
    return self.g

  def get_loss(self):
    firstpart = (-1*(self.Y.T))*(np.log(self.g))
    secondpart = ((1-Y).T)*(np.log(1-self.g))
    thirdpart = (firstpart-secondpart)
    self.J = np.mean(thirdpart)
    return self.J

In [ ]:
import numpy as np

X = np.random.normal(0,1,size=(5,10)).T
m = X.shape[1]
theta = np.random.normal(0,1,size=(m,1))
Y = np.random.randint(2,size=(m,1))
print(X)
print(theta)
print(Y)

[[-0.40810334  0.73196693  1.56365301 -0.96188213 -0.67084772]
 [ 0.83576972 -0.44988954  0.93655164  1.64625867  0.36934559]
 [-0.3826615   0.22401622 -0.44073071  0.48348971 -1.16716552]
 [ 1.1804394  -0.01992631 -0.81850534 -0.18827069 -1.47601995]
 [ 0.25491689 -0.78544156 -0.20619438 -0.47171802  2.42270301]
 [-0.21628769 -0.83016081 -0.70690263  2.06601923 -0.69557865]
 [-1.11260668 -0.68255937 -0.54888195  0.8542802  -0.18689897]
 [ 0.91234955 -0.35129994  1.31268653 -1.56133915  0.08154536]
 [-1.23501467  0.65339664 -0.60400562  0.12813037 -1.14836363]
 [-0.37123474 -1.31954555  0.35098363 -0.15923855  1.22400868]]
[[ 0.08368961]
 [-2.02044799]
 [-1.40897972]
 [-0.42933591]
 [ 1.14787936]]
[[0]
 [1]
 [1]
 [0]
 [0]]


In [ ]:
Logit_test = LRegression(X,Y,theta)
print("Vector product of X and theta: \n",Logit_test.get_vectorproduct())
print("\nShape of hypothesis:",Logit_test.get_shapeh())
print("\nHypothesis of the Logistic Regression:\n",Logit_test.get_hypothesis())
print("\nLoss of the Logistic Regression:\n",Logit_test.get_loss())

Vector product of X and theta: 
 [[-4.07329222]
 [-0.62349241]
 [-1.41100198]
 [-0.32115347]
 [ 4.88229768]
 [ 0.96975054]
 [ 1.478015  ]
 [-0.29946806]
 [-1.94567404]
 [ 3.61385698]]

Shape of hypothesis: (10, 1)

Hypothesis of the Logistic Regression:
 [[0.01673638]
 [0.34898757]
 [0.19607607]
 [0.42039466]
 [0.99247744]
 [0.72506977]
 [0.81427257]
 [0.42568753]
 [0.12502583]
 [0.97375941]]

Loss of the Logistic Regression:
 1.2494980127630797
